### ISSUE TITLE
Feature request angled gradients

### ISSUE THREAD

**Issue by Code4SAFrankie** [kengoon/KivyGradient#1]
A left bottom to top right gradient or left top to bottom right gradient would also be awesome, since these are probably most used in design. Arbitrary angle would also be cool and could even replace the need for other types.

**Comment by kengoon** [comment]
@Code4SAFrankie if you can do that, you are welcome to open a PR, as I am not very much interested in this project, I only took an idea someone created in 2015 and made it much simpler and easier to use and access.
